# markdown が格納されているフォルダ名 (ワークスペースフォルダからの相対パス)
mdRoot: docs-src
# 発行先のフォルダ名 (ワークスペースフォルダからの相対パス)
pubRoot: docs
# 言語の指定 (スペース区切りで複数言語の指定可)
lang: ja #en
# html スタイルシートの指定
#htmlTemplate: styles/html/html-style.css
# html テンプレートの指定
#htmlTemplate: styles/html/html-template.html
# html (self-contain) テンプレートの指定
#htmlSelfContainTemplate: styles/html/html-template.html
# html における toc 出力要否 (false / true)
#htmlTocEnable: true
# html における toc の深さ
#htmlTocDepth: 3
# docx テンプレートの指定
#docxTemplate: styles/docx/docx-style.dotx
# date 自動設定の有無 (false / true)
autoSetDate: true
# author 自動設定の有無 (false / true)
autoSetAuthor: true
